export * from './types';
export * from './presets';
export * from './backgrounds';
export * from './storage';
export * from './color-utils';
export * from './design-overrides';
export * from './background-layout';
export * from './audio-reactive';
export * from './audio-reactive/overlays';
export type { BarAlignment } from '@/src/recorder/waveform';
export { renderThemePreview } from '@/src/recorder/waveform';
